name: C CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: makeBuild
      working-directory: .
      run: mkdir build
    - name: compilation
      working-directory: build/
      run: |
        cmake ..
        make .
    - name: runTests
      working-directory: build/
      run: ctest -V
