name: C CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: makeBuild
      run: mkdir build
    - name: compilation
      run: cmake ..
            make
    - name: runTests
      run: ctest -V
